// Seed data for Firestore
module.exports = {
  doctors: [
    { id: 'dr_001', name: 'Dr. Divya K', email: 'divya@luminest.care', avatar: 'DK', specialty: 'Reproductive Endocrinology' },
    { id: 'dr_002', name: 'Dr. Praveen', email: 'praveen@luminest.care', avatar: 'PR', specialty: 'Fertility & Lifestyle Medicine' },
  ],
  patients: [
    { id: 'couple_001', name: 'Priya & Arjun', email: 'priya.arjun@email.com', package: 'Sprout', week: 3, cycleDay: 13, status: 'On track', concern: 'Irregular cycles', tryingSince: '8 months', assignedDoctor: 'dr_001', joinedAt: '2026-04-28T10:00:00Z' },
    { id: 'couple_002', name: 'Meera & Kiran', email: 'meera.kiran@email.com', package: 'Bloom', week: 5, cycleDay: 8, status: 'Needs attention', concern: 'Low energy', tryingSince: '1 year', assignedDoctor: 'dr_001', joinedAt: '2026-04-14T10:00:00Z' },
    { id: 'couple_003', name: 'Anika & Rohan', email: 'anika.rohan@email.com', package: 'Seed', week: 2, cycleDay: 20, status: 'New check-in', concern: 'Cycle awareness', tryingSince: '4 months', assignedDoctor: 'dr_002', joinedAt: '2026-05-05T10:00:00Z' },
    { id: 'couple_004', name: 'Sneha & Vikram', email: 'sneha.vikram@email.com', package: 'Bloom', week: 6, cycleDay: 15, status: 'On track', concern: 'Timing optimization', tryingSince: '6 months', assignedDoctor: 'dr_002', joinedAt: '2026-04-07T10:00:00Z' },
    { id: 'couple_005', name: 'Ritu & Deepak', email: 'ritu.deepak@email.com', package: 'Sprout', week: 1, cycleDay: 3, status: 'New', concern: 'Getting started', tryingSince: '3 months', assignedDoctor: 'dr_001', joinedAt: '2026-05-12T10:00:00Z' },
  ],
  checkins: [
    { id: 'ci_001', coupleId: 'couple_001', coupleName: 'Priya & Arjun', week: 3, status: 'pending', summary: 'Energy is steady. Cervical mucus changed to watery yesterday. Asking if timing is right.', details: { health: 'Energy has improved since last week. Sleeping 7-8 hours consistently.', improved: 'Sleep quality, energy levels in the morning.', worsened: 'Mild bloating in the evenings.', cycleObs: 'CM changed from creamy to watery on Day 12. Slight ovulation pain on left side.', emotional: 'Good', question: 'Is the watery CM a good sign for fertile window timing?' }, submittedAt: '2026-05-16T08:30:00Z' },
    { id: 'ci_002', coupleId: 'couple_002', coupleName: 'Meera & Kiran', week: 5, status: 'pending', summary: 'Stress is high this week and sleep dropped to 5 hours.', details: { health: 'Work stress peaked this week. Headaches returned.', improved: 'Diet is consistent with plan.', worsened: 'Sleep dropped to 5 hours on 3 nights. Headaches.', cycleObs: 'Cycle appears regular but CM is minimal.', emotional: 'Struggling', question: 'Should I take a break from tracking when stressed?' }, submittedAt: '2026-05-15T19:45:00Z' },
    { id: 'ci_003', coupleId: 'couple_003', coupleName: 'Anika & Rohan', week: 2, status: 'pending', summary: 'Completed daily food and movement tasks for six days.', details: { health: 'Feeling good overall. Started morning walks.', improved: 'Consistency with food logging and movement.', worsened: 'Nothing specific.', cycleObs: 'Learning to identify CM types. Currently in luteal phase.', emotional: 'Good', question: 'How long before I can expect clearer CM patterns?' }, submittedAt: '2026-05-16T14:20:00Z' },
    { id: 'ci_004', coupleId: 'couple_004', coupleName: 'Sneha & Vikram', week: 6, status: 'responded', summary: 'Egg-white CM observed on Day 13 and 14. BBT shift confirmed.', details: { health: 'Great week. Energy and sleep are stable.', improved: 'CM tracking confidence. BBT pattern is clear.', worsened: 'Nothing.', cycleObs: 'EWCM on Day 13-14, BBT rose by 0.3°C on Day 15.', emotional: 'Excellent', question: 'Is the BBT shift enough to confirm ovulation?' }, submittedAt: '2026-05-14T09:00:00Z', response: { body: 'Excellent observations! The BBT shift of 0.3°C sustained for 3+ days, combined with EWCM, strongly suggests ovulation occurred.', respondedBy: 'dr_002', respondedByName: 'Dr. Praveen', respondedAt: '2026-05-14T16:30:00Z' } },
    { id: 'ci_005', coupleId: 'couple_001', coupleName: 'Priya & Arjun', week: 2, status: 'responded', summary: 'Started tracking CM for the first time. Sleep has improved with evening routine.', details: { health: 'Good energy. Started evening wind-down routine.', improved: 'Sleep onset time reduced from 45 min to 20 min.', worsened: 'Mild cramps during period days.', cycleObs: 'Period ended Day 5. CM currently dry/sticky.', emotional: 'Good', question: 'When should I expect CM to change to creamy?' }, submittedAt: '2026-05-09T10:15:00Z', response: { body: 'Great progress on your sleep routine! CM typically transitions from dry → sticky → creamy around Days 8-10.', respondedBy: 'dr_001', respondedByName: 'Dr. Divya K', respondedAt: '2026-05-09T17:00:00Z' } },
  ],
  reports: [
    { id: 'rpt_001', coupleId: 'couple_001', coupleName: 'Priya & Arjun', date: '2026-05-16', energy: 'Good', mood: 'Good', sleep: 'Good', mucus: 'Watery', symptoms: ['Breast tenderness'], notes: 'Noticed watery CM today. Feeling positive.', createdAt: '2026-05-16T07:30:00Z' },
    { id: 'rpt_002', coupleId: 'couple_001', coupleName: 'Priya & Arjun', date: '2026-05-15', energy: 'Good', mood: 'Good', sleep: 'Okay', mucus: 'Creamy / Lotion-like', symptoms: [], notes: 'Steady day. Walked 30 min.', createdAt: '2026-05-15T08:00:00Z' },
    { id: 'rpt_003', coupleId: 'couple_002', coupleName: 'Meera & Kiran', date: '2026-05-16', energy: 'Low', mood: 'Low', sleep: 'Poor', mucus: 'Dry / None', symptoms: ['Headache', 'Bloating'], notes: 'Bad night. Headache since morning.', createdAt: '2026-05-16T09:00:00Z' },
    { id: 'rpt_004', coupleId: 'couple_003', coupleName: 'Anika & Rohan', date: '2026-05-16', energy: 'High', mood: 'Great', sleep: 'Great', mucus: 'Sticky', symptoms: [], notes: 'Morning walk and healthy breakfast!', createdAt: '2026-05-16T06:45:00Z' },
    { id: 'rpt_005', coupleId: 'couple_004', coupleName: 'Sneha & Vikram', date: '2026-05-16', energy: 'Good', mood: 'Good', sleep: 'Good', mucus: 'Egg-white (stretchy)', symptoms: ['Cramps'], notes: 'EWCM observed. Mild ovulation cramps.', createdAt: '2026-05-16T07:15:00Z' },
    { id: 'rpt_006', coupleId: 'couple_001', coupleName: 'Priya & Arjun', date: '2026-05-14', energy: 'Okay', mood: 'Neutral', sleep: 'Good', mucus: 'Creamy / Lotion-like', symptoms: [], notes: 'Regular day.', createdAt: '2026-05-14T08:30:00Z' },
    { id: 'rpt_007', coupleId: 'couple_002', coupleName: 'Meera & Kiran', date: '2026-05-15', energy: 'Okay', mood: 'Neutral', sleep: 'Okay', mucus: 'Dry / None', symptoms: ['Bloating'], notes: 'Ate well but energy is flat.', createdAt: '2026-05-15T08:30:00Z' },
    { id: 'rpt_008', coupleId: 'couple_004', coupleName: 'Sneha & Vikram', date: '2026-05-15', energy: 'Good', mood: 'Good', sleep: 'Great', mucus: 'Watery', symptoms: [], notes: 'CM changing to watery.', createdAt: '2026-05-15T07:00:00Z' },
  ],
  notes: [
    { id: 'note_001', title: 'Week 3 guidance', body: 'You are approaching your fertile window. Keep tracking mucus changes and prioritize sleep for the next few nights.', tone: 'sage', targetCoupleId: 'couple_001', authorId: 'dr_001', authorName: 'Dr. Divya K', createdAt: '2026-05-15T10:00:00Z' },
    { id: 'note_002', title: 'Nutrition focus', body: 'Add one protein-rich snack in the evening to keep energy stable.', tone: 'gold', targetCoupleId: null, authorId: 'dr_001', authorName: 'Dr. Divya K', createdAt: '2026-05-14T11:00:00Z' },
    { id: 'note_003', title: 'Sleep protocol for stress weeks', body: 'When stress is high: no screens 1 hour before bed, chamomile tea, 10 min guided breathing.', tone: 'sage', targetCoupleId: 'couple_002', authorId: 'dr_001', authorName: 'Dr. Divya K', createdAt: '2026-05-13T09:00:00Z' },
    { id: 'note_004', title: 'CM tracking beginner tips', body: 'Check CM at the same time each day, ideally after your first bathroom visit. Note both the appearance and the sensation.', tone: 'sage', targetCoupleId: 'couple_003', authorId: 'dr_002', authorName: 'Dr. Praveen', createdAt: '2026-05-12T15:00:00Z' },
  ],
};
